export const GET_USER_LOCATION = 'GET_USER_LOCATION';
export const ADD_FEATURE_TYPE = 'ADD_FEATURE_TYPE';
export const DEL_FEATURE_TYPE = 'DEL_FEATURE_TYPE';
export const EDIT_FEATURE_TYPE = 'EDIT_FEATURE_TYPE';
export const ADD_PROJECT = 'ADD_PROJECT';
export const DEL_PROJECT = 'DEL_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const ADD_FEATURES_TO_PROJECT = 'ADD_FEATURES_TO_PROJECT';